set -e

UNIQUE_PREFIX=$1
ENVIRONMENT=$2
CLUSTER_LOCATION_ACRONYM=$3
DATABASE_NAME=$4
MANAGED_IDENTITY_CLIENT_ID=$5

CLUSTER_RESOURCE_GROUP_NAME=$UNIQUE_PREFIX-$ENVIRONMENT-$CLUSTER_LOCATION_ACRONYM
MANAGED_IDENTITY_NAME=$CLUSTER_RESOURCE_GROUP_NAME-$4
POSTGRES_SERVER_NAME=$CLUSTER_RESOURCE_GROUP_NAME
POSTGRES_HOST=$POSTGRES_SERVER_NAME.postgres.database.azure.com

ACCESS_TOKEN=$(az account get-access-token --resource-type oss-rdbms --query accessToken --output tsv)
ENTRA_USER=$(az postgres flexible-server microsoft-entra-admin list --resource-group $CLUSTER_RESOURCE_GROUP_NAME --server-name $POSTGRES_SERVER_NAME --query "[0].principalName" --output tsv)

echo "$(date +"%Y-%m-%dT%H:%M:%S") Granting $MANAGED_IDENTITY_NAME permissions on $POSTGRES_HOST/$DATABASE_NAME"

PGPASSWORD=$ACCESS_TOKEN psql -v ON_ERROR_STOP=1 "host=$POSTGRES_HOST dbname=postgres user='$ENTRA_USER' sslmode=verify-full sslrootcert=system" << EOF
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '$MANAGED_IDENTITY_NAME') THEN
        PERFORM pgaadauth_create_principal('$MANAGED_IDENTITY_NAME', false, false);
    END IF;
END
\$\$;
EOF

PGPASSWORD=$ACCESS_TOKEN psql -v ON_ERROR_STOP=1 "host=$POSTGRES_HOST dbname=$DATABASE_NAME user='$ENTRA_USER' sslmode=verify-full sslrootcert=system" << EOF
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
GRANT CONNECT ON DATABASE "$DATABASE_NAME" TO "$MANAGED_IDENTITY_NAME";
GRANT USAGE ON SCHEMA public TO "$MANAGED_IDENTITY_NAME";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "$MANAGED_IDENTITY_NAME";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "$MANAGED_IDENTITY_NAME";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "$MANAGED_IDENTITY_NAME";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO "$MANAGED_IDENTITY_NAME";
EOF
