# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # NPM dependencies for frontend applications
  - package-ecosystem: "npm"
    directory: "/application"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    secrets:
      SONAR_TOKEN: true

  # .NET dependencies for backend applications
  - package-ecosystem: "dotnet-sdk"
    directory: "/application"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    secrets:
      SONAR_TOKEN: true

  # .NET dependencies for developer CLI
  - package-ecosystem: "dotnet-sdk"
    directory: "/developer-cli"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    secrets:
      SONAR_TOKEN: true

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*"
    secrets:
      SONAR_TOKEN: true
