#!/usr/bin/env node

/**
 * This script is used to run the Biome binary from VS Code until workspaces are supported.
 *
 * ref: https://github.com/biomejs/biome-vscode/issues/201
 */

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

// Get the path of the application
const applicationPath = path.join(__dirname, "..", "..", "..");

// Set the BIOME_CONFIG_PATH environment variable to the path of the biome.json file
const configPath = path.join(applicationPath, "biome.json");

if (!fs.existsSync(configPath)) {
  console.error(`biome.json not found in ${applicationPath}. Please run \`biome init\` to create the file.`);
  process.exit(1);
}

// Get the path of the biome module
const biomePath = require.resolve("@biomejs/biome/bin/biome");

// Load the biome module
const result = spawnSync(biomePath, process.argv.slice(2), {
  shell: false,
  stdio: "inherit",
  cwd: applicationPath,
  env: {
    ...process.env,
    // Set the BIOME_CONFIG_PATH environment variable pointing to the directory of the biome.json file
    BIOME_CONFIG_PATH: path.dirname(configPath)
  }
});

if (result.error) {
  throw result.error;
}

process.exit(result.status);
