@host = https://localhost:8443
@tenantId = acme
@tenantName = Acme
@email = foo@bar.dk
@password = !mySecretPassword123
@accountRegistrationId = xx
@oneTimePassword = 123456

### User account registration of a new tenant and owner
POST {{host}}/api/account-registrations/start
Content-Type: application/json

{
  "email": "{{email}}"
}

### User account registration of a new tenant and owner
POST {{host}}/api/account-registrations/{{accountRegistrationId}}/confirm-email
Content-Type: application/json

{
    "oneTimePassword": "{{oneTimePassword}}"
}

### User account registration of a new tenant and owner
POST {{host}}/api/tenants
Content-Type: application/json

{
    "accountRegistrationId": "{{accountRegistrationId}}",
    "subdomain": "{{tenantId}}",
    "name": "{{tenantName}}"
}

### User login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get Secret
GET {{host}}/api/secret

### Get Secret Role Owner
GET {{host}}/api/secretOwner

### Get Secret Role User
GET {{host}}/api/secretUser

### Logout
POST {{host}}/api/auth/logout