@host = https://localhost:8443
@tenantId = acme
@email = foo@bar.dk
@password = !mySecretPassword123

### User registration of a new user and tenant
POST {{host}}/api/account-registrations/start
Content-Type: application/json

{
  "email": "{{email}}"
}

### User login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Get Secret
GET {{host}}/api/secret

### Get Secret Role Owner
GET {{host}}/api/secretOwner

### Get Secret Role User
GET {{host}}/api/secretUser

### Logout
POST {{host}}/api/auth/logout